#include "andor_camera.h"

                             /**************************************
                             *    ANDOR SDK FEATURES DEFINITIONS   *
                             ***************************************/

//
//  Names and types correspond to ANDOR SDK version 3.11
//



ANDOR_Camera::AndorFeatureNameMap DEFAULT_ANDOR_SDK_FEATURES = {
    {L"AccumulateCount", ANDOR_Camera::BoolType},
    {L"AlternatingReadoutDirection", ANDOR_Camera::BoolType},
    {L"AOIBinning", ANDOR_Camera::EnumType},
    {L"AOIHBin", ANDOR_Camera::IntType},
    {L"AOIHeight", ANDOR_Camera::IntType},
    {L"AOILayout", ANDOR_Camera::EnumType},
    {L"AOILeft", ANDOR_Camera::IntType},
    {L"AOIStride", ANDOR_Camera::IntType},
    {L"AOITop", ANDOR_Camera::IntType},
    {L"AOIVBin", ANDOR_Camera::IntType},
    {L"AOIWidth", ANDOR_Camera::IntType},
    {L"AuxiliaryOutSource", ANDOR_Camera::EnumType},
    {L"AuxOutSourceTwo", ANDOR_Camera::EnumType},
    {L"BackoffTemperatureOffset", ANDOR_Camera::FloatType},
    {L"Baseline", ANDOR_Camera::IntType},
    {L"BitDepth", ANDOR_Camera::EnumType},
    {L"BufferOverflowEvent", ANDOR_Camera::IntType},
    {L"BytesPerPixel", ANDOR_Camera::FloatType},
    {L"CameraAcquiring", ANDOR_Camera::BoolType},
    {L"CameraFamily", ANDOR_Camera::StringType},
    {L"CameraMemory", ANDOR_Camera::IntType},
    {L"CameraModel", ANDOR_Camera::StringType},
    {L"CameraName", ANDOR_Camera::StringType},
    {L"CameraPresent", ANDOR_Camera::BoolType},
    {L"ColourFilter", ANDOR_Camera::EnumType},
    {L"ControllerID", ANDOR_Camera::StringType},
    {L"CoolerPower", ANDOR_Camera::FloatType},
    {L"CycleMode", ANDOR_Camera::EnumType},
    {L"DDR2Type", ANDOR_Camera::StringType},
    {L"DeviceCount", ANDOR_Camera::IntType},
    {L"DeviceVideoIndex", ANDOR_Camera::IntType},
    {L"DisableShutter", ANDOR_Camera::BoolType},
    {L"DriverVersion", ANDOR_Camera::StringType},
    {L"ElectronicShutteringMode", ANDOR_Camera::EnumType},
    {L"EventEnable", ANDOR_Camera::BoolType},
    {L"EventsMissedEvent", ANDOR_Camera::IntType},
    {L"EventSelector", ANDOR_Camera::EnumType},
    {L"ExposedPixelHeight", ANDOR_Camera::IntType},
    {L"ExposureTime", ANDOR_Camera::FloatType},
    {L"ExposureEndEvent", ANDOR_Camera::IntType},
    {L"ExposureStartEvent", ANDOR_Camera::IntType},
    {L"ExternalIOReadout", ANDOR_Camera::BoolType},
    {L"ExternalTriggerDelay", ANDOR_Camera::FloatType},
    {L"FanSpeed", ANDOR_Camera::EnumType},
    {L"FastAOIFrameRateEnable", ANDOR_Camera::BoolType},
    {L"FirmwareVersion", ANDOR_Camera::StringType},
    {L"ForceShutterOpen", ANDOR_Camera::BoolType},
    {L"FrameCount", ANDOR_Camera::IntType},
    {L"FrameInterval", ANDOR_Camera::FloatType},
    {L"FrameIntervalTiming", ANDOR_Camera::BoolType},
    {L"FrameRate", ANDOR_Camera::FloatType},
    {L"FullAOIControl", ANDOR_Camera::BoolType},
    {L"HeatSinkTemperature", ANDOR_Camera::FloatType},
    {L"ImageSizeBytes", ANDOR_Camera::IntType},
    {L"InputVoltage", ANDOR_Camera::FloatType},
    {L"InterfaceType", ANDOR_Camera::StringType},
    {L"IOControl", ANDOR_Camera::EnumType},
    {L"IODirection", ANDOR_Camera::EnumType},
    {L"IOState", ANDOR_Camera::BoolType},
    {L"IOInvert", ANDOR_Camera::BoolType},
    {L"IOSelector", ANDOR_Camera::EnumType},
    {L"IRPreFlashEnable", ANDOR_Camera::BoolType},
    {L"KeepCleanEnable", ANDOR_Camera::BoolType},
    {L"KeepCleanPostExposureEnable", ANDOR_Camera::BoolType},
    {L"LineScanSpeed", ANDOR_Camera::FloatType},
    {L"MaxInterfaceTransferRate", ANDOR_Camera::FloatType},
    {L"MetadataEnable", ANDOR_Camera::BoolType},
    {L"MetadataFrame", ANDOR_Camera::BoolType},
    {L"MetadataTimestamp", ANDOR_Camera::BoolType},
    {L"MicrocodeVersion", ANDOR_Camera::StringType},
    {L"MultitrackBinned", ANDOR_Camera::BoolType},
    {L"MultitrackCount", ANDOR_Camera::IntType},
    {L"MultitrackEnd", ANDOR_Camera::IntType},
    {L"MultitrackSelector", ANDOR_Camera::IntType},
    {L"MultitrackStart", ANDOR_Camera::IntType},
    {L"Overlap", ANDOR_Camera::BoolType},
    {L"PixelEncoding", ANDOR_Camera::EnumType},
    {L"PixelHeight", ANDOR_Camera::FloatType},
    {L"PixelReadoutRate", ANDOR_Camera::EnumType},
    {L"PixelWidth", ANDOR_Camera::FloatType},
    {L"PortSelector", ANDOR_Camera::IntType},
    #ifdef ANDOR_CAMERA_DEPRECATED_ENABLED
    {L"PreAmpGain", ANDOR_Camera::EnumType},
    {L"PreAmpGainChannel", ANDOR_Camera::EnumType},
    {L"PreAmpGainControl", ANDOR_Camera::EnumType},
    {L"PreAmpGainSelector", ANDOR_Camera::EnumType},
    #endif
    {L"PreAmpGainValue", ANDOR_Camera::IntType},
    {L"PreAmpOffsetValue", ANDOR_Camera::IntType},
    {L"ReadoutTime", ANDOR_Camera::FloatType},
    {L"RollingShutterGlobalClear", ANDOR_Camera::BoolType},
    {L"RowNExposureEndEvent", ANDOR_Camera::IntType},
    {L"RowNExposureStartEvent", ANDOR_Camera::IntType},
    {L"RowReadTime", ANDOR_Camera::FloatType},
    {L"ScanSpeedControlEnable", ANDOR_Camera::BoolType},
    {L"SensorCooling", ANDOR_Camera::BoolType},
    {L"SensorHeight", ANDOR_Camera::IntType},
    {L"SensorModel", ANDOR_Camera::StringType},
    {L"SensorReadoutMode", ANDOR_Camera::EnumType},
    {L"SensorType", ANDOR_Camera::EnumType},
    {L"SensorTemperature", ANDOR_Camera::FloatType},
    {L"SensorWidth", ANDOR_Camera::IntType},
    {L"SerialNumber", ANDOR_Camera::StringType},
    {L"ShutterAmpControl", ANDOR_Camera::BoolType},
    {L"ShutterMode", ANDOR_Camera::EnumType},
    {L"ShutterOutputMode", ANDOR_Camera::EnumType},
    {L"ShutterState", ANDOR_Camera::BoolType},
    {L"ShutterStrobePeriod", ANDOR_Camera::FloatType},
    {L"ShutterStrobePosition", ANDOR_Camera::FloatType},
    {L"ShutterTransferTime", ANDOR_Camera::FloatType},
    {L"SimplePreAmpGainControl", ANDOR_Camera::EnumType},
    {L"SoftwareVersion", ANDOR_Camera::StringType},
    {L"SpuriousNoiseFilter", ANDOR_Camera::BoolType},
    {L"StaticBlemishCorrection", ANDOR_Camera::BoolType},
    #ifdef ANDOR_CAMERA_DEPRECATED_ENABLED
    {L"TargetSensorTemperature", ANDOR_Camera::FloatType},
    #endif
    {L"TemperatureControl", ANDOR_Camera::EnumType},
    {L"TemperatureStatus", ANDOR_Camera::EnumType},
    {L"TimestampClock", ANDOR_Camera::IntType},
    {L"TimestampClockFrequency", ANDOR_Camera::IntType},
    {L"TransmitFrames", ANDOR_Camera::BoolType},
    {L"TriggerMode", ANDOR_Camera::EnumType},
    {L"UsbProductId", ANDOR_Camera::IntType},
    {L"UsbDeviceId", ANDOR_Camera::IntType},
    {L"VerticallyCentreAOI", ANDOR_Camera::BoolType}
};
